version: '2'

services:
  yujvidya-web:
    image: yujvidya.azurecr.io/yujvidya-web:BuildNumber
    ports:
      - "5002:5002"
    depends_on:
      - yujvidya

  yujvidya:
    image: yujvidya.azurecr.io/yujvidya:BuildNumber
    ports:
      - "5001:5001"
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
