version: '3.4'

services:
  yujvidya-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  yujvidya:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
